# Generated by Django 4.1.1 on 2022-09-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_remove_destinations_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
